import { useState, useMemo } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useUniGuard } from "@/lib/uniguard/store";
import { FileDown, Calendar as CalendarIcon } from "lucide-react";
import { cn } from "@/lib/utils";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import { format } from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "sonner";

interface Props {
  open: boolean;
  onOpenChange: (o: boolean) => void;
  defaultDate?: string;
}

export function ExportDialog({ open, onOpenChange, defaultDate }: Props) {
  const { schedule, staff, rooms, slots } = useUniGuard();
  const [mode, setMode] = useState<"single" | "full">("single");
  const [date, setDate] = useState<Date>(defaultDate ? new Date(defaultDate) : new Date());
  const [university, setUniversity] = useState("Cairo University");
  const [department, setDepartment] = useState("Faculty of Engineering");
  const [season, setSeason] = useState("Final Exams — Spring 2026");

  const availableDates = useMemo(() => [...new Set(schedule.map((e) => e.date))].sort(), [schedule]);

  const onExport = () => {
    if (schedule.length === 0) {
      toast.error("Nothing to export — generate a schedule first.");
      return;
    }
    const staffMap = new Map(staff.map((s) => [s.id, s]));
    const roomMap = new Map(rooms.map((r) => [r.id, r]));
    const slotMap = new Map(slots.map((s) => [s.id, s]));

    const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();

    const drawHeader = (subTitle: string) => {
      doc.setFillColor(31, 64, 135);
      doc.rect(0, 0, pageW, 70, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.text(university, 40, 30);
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text(department, 40, 48);
      doc.setFontSize(10);
      doc.text(season, 40, 62);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("Exam Invigilation Schedule", pageW - 40, 32, { align: "right" });
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(subTitle, pageW - 40, 50, { align: "right" });
      doc.setTextColor(0, 0, 0);
    };

    const drawFooter = () => {
      const h = doc.internal.pageSize.getHeight();
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text(`Generated by UniGuard · ${format(new Date(), "PPp")}`, 40, h - 20);
      doc.text(`Page ${doc.getNumberOfPages()}`, pageW - 40, h - 20, { align: "right" });
      doc.setTextColor(0, 0, 0);
    };

    const datesToExport = mode === "single" ? [format(date, "yyyy-MM-dd")] : [...new Set(schedule.map((e) => e.date))].sort();
    let firstPage = true;

    for (const d of datesToExport) {
      const entries = schedule.filter((e) => e.date === d).sort((a, b) => a.slotId.localeCompare(b.slotId));
      if (entries.length === 0) continue;
      if (!firstPage) doc.addPage();
      firstPage = false;
      const dayLabel = entries[0].day;
      drawHeader(`${dayLabel}, ${d}`);

      let y = 90;
      for (const e of entries) {
        const slot = slotMap.get(e.slotId);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(31, 64, 135);
        doc.text(`${slot?.label ?? e.slotId}`, 40, y);
        doc.setTextColor(0, 0, 0);

        const rows = e.assignments.map((a) => {
          const room = roomMap.get(a.roomId);
          const doc1 = a.doctorId ? staffMap.get(a.doctorId)?.name ?? "—" : "— UNASSIGNED —";
          const tas = a.taIds.map((id) => (id ? staffMap.get(id)?.name ?? "—" : "—")).join("\n");
          return [room?.name ?? "—", String(room?.capacity ?? "—"), a.subject ?? "—", doc1 + (a.sharedDoctor ? "  (Shared)" : ""), tas];
        });

        autoTable(doc, {
          startY: y + 8,
          head: [["Room", "Cap.", "Subject", "Doctor", "Teaching Assistants"]],
          body: rows,
          theme: "grid",
          headStyles: { fillColor: [241, 245, 249], textColor: [31, 64, 135], fontStyle: "bold", fontSize: 9 },
          bodyStyles: { fontSize: 9, cellPadding: 6 },
          alternateRowStyles: { fillColor: [250, 250, 252] },
          margin: { left: 40, right: 40 },
          columnStyles: { 0: { cellWidth: 90 }, 1: { cellWidth: 45, halign: "center" }, 2: { cellWidth: 130 }, 3: { cellWidth: 160 } },
        });
        // @ts-ignore
        y = (doc as any).lastAutoTable.finalY + 24;
        if (y > doc.internal.pageSize.getHeight() - 80) {
          drawFooter();
          doc.addPage();
          drawHeader(`${dayLabel}, ${d} (cont.)`);
          y = 90;
        }
      }
      drawFooter();
    }

    const filename = mode === "single"
      ? `UniGuard_${format(date, "yyyy-MM-dd")}.pdf`
      : `UniGuard_FullSchedule_${format(new Date(), "yyyy-MM-dd")}.pdf`;
    doc.save(filename);
    toast.success("PDF exported", { description: filename });
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2"><FileDown className="h-4 w-4" /> Export Schedule PDF</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={() => setMode("single")}
              className={cn("rounded-lg border p-3 text-left transition-smooth", mode === "single" ? "border-primary bg-primary/5" : "border-border")}
            >
              <div className="text-sm font-semibold">Single day</div>
              <div className="text-[11px] text-muted-foreground">Printable sheet for the board</div>
            </button>
            <button
              onClick={() => setMode("full")}
              className={cn("rounded-lg border p-3 text-left transition-smooth", mode === "full" ? "border-primary bg-primary/5" : "border-border")}
            >
              <div className="text-sm font-semibold">Full period</div>
              <div className="text-[11px] text-muted-foreground">All days, multi-page report</div>
            </button>
          </div>

          {mode === "single" && (
            <div>
              <Label>Exam date</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="w-full justify-start text-left font-normal">
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {format(date, "PPP")}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar mode="single" selected={date} onSelect={(d) => d && setDate(d)} initialFocus className="p-3 pointer-events-auto" />
                </PopoverContent>
              </Popover>
              {availableDates.length > 0 && !availableDates.includes(format(date, "yyyy-MM-dd")) && (
                <p className="text-[11px] text-warning mt-1.5">No schedule on this date. Available: {availableDates.join(", ")}</p>
              )}
            </div>
          )}

          <div className="grid grid-cols-1 gap-3 pt-2 border-t border-border">
            <div className="text-[10px] uppercase tracking-wider text-muted-foreground font-medium">Header information</div>
            <div>
              <Label className="text-xs">University</Label>
              <Input value={university} onChange={(e) => setUniversity(e.target.value)} maxLength={80} />
            </div>
            <div>
              <Label className="text-xs">Department / Faculty</Label>
              <Input value={department} onChange={(e) => setDepartment(e.target.value)} maxLength={80} />
            </div>
            <div>
              <Label className="text-xs">Exam season</Label>
              <Input value={season} onChange={(e) => setSeason(e.target.value)} maxLength={80} />
            </div>
          </div>
        </div>
        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button onClick={onExport} className="gap-2"><FileDown className="h-4 w-4" /> Export PDF</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
