import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { format } from "date-fns";
import { Room, ScheduleEntry, Slot, Staff } from "./types";

export interface ExportContext {
  schedule: ScheduleEntry[];
  staff: Staff[];
  rooms: Room[];
  slots: Slot[];
  brand: { appName: string; university: string; department: string; examPeriod: string; logoDataUrl: string | null };
}

const timeLabel = (slot?: Slot) => slot ? `${slot.startTime} – ${slot.endTime}` : "—";

const subjectFor = (a: { subjectName?: string; subjectCode?: string }, slot?: Slot) => ({
  name: a.subjectName ?? slot?.subjectName ?? "—",
  code: a.subjectCode ?? slot?.subjectCode ?? "",
});

export function exportPdf(ctx: ExportContext, opts: { mode: "single" | "full"; date?: string }) {
  const { schedule, staff, rooms, slots, brand } = ctx;
  const staffMap = new Map(staff.map((s) => [s.id, s]));
  const roomMap = new Map(rooms.map((r) => [r.id, r]));
  const slotMap = new Map(slots.map((s) => [s.id, s]));
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const generatedAt = format(new Date(), "PPp");

  const drawHeader = (subTitle: string) => {
    doc.setFillColor(248, 250, 252);
    doc.rect(0, 0, pageW, 72, "F");
    let textX = 40;
    if (brand.logoDataUrl) {
      try { doc.addImage(brand.logoDataUrl, "PNG", 40, 16, 40, 40); textX = 92; } catch {}
    }
    doc.setTextColor(31, 64, 135); doc.setFont("helvetica", "bold"); doc.setFontSize(18);
    doc.text(brand.university, textX, 32);
    doc.setTextColor(70, 80, 95); doc.setFontSize(10); doc.setFont("helvetica", "normal");
    doc.text(`${brand.department} · ${brand.examPeriod}`, textX, 50);
    doc.setFont("helvetica", "bold"); doc.setFontSize(14); doc.setTextColor(15, 23, 42);
    doc.text(`${brand.appName} · Exam Schedule`, pageW - 40, 32, { align: "right" });
    doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    doc.text(subTitle, pageW - 40, 50, { align: "right" });
  };
  const drawFooter = () => {
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(8); doc.setTextColor(120, 120, 120);
    doc.text(`Generated by ${brand.appName} on ${generatedAt}`, 40, h - 20);
    doc.text(`Page ${doc.getNumberOfPages()}`, pageW - 40, h - 20, { align: "right" });
  };

  const datesToExport = opts.mode === "single"
    ? [opts.date!].filter(Boolean)
    : [...new Set(schedule.map((e) => e.date))].sort();
  let firstPage = true;
  for (const d of datesToExport) {
    const entries = schedule.filter((e) => e.date === d).sort((a, b) => a.slotId.localeCompare(b.slotId));
    if (entries.length === 0) continue;
    if (!firstPage) doc.addPage();
    firstPage = false;
    drawHeader(`${entries[0].day}, ${d}`);
    const rows = entries.flatMap((e) => e.assignments.map((a) => {
      const slot = slotMap.get(e.slotId); const room = roomMap.get(a.roomId);
      const subj = subjectFor(a, slot);
      const chief = a.chiefInvigilatorId ? staffMap.get(a.chiefInvigilatorId)?.name ?? "—" : "— UNASSIGNED —";
      const invigilators = a.invigilatorIds.map((id) => id ? staffMap.get(id)?.name ?? "—" : "— Missing —").join("\n");
      return [
        timeLabel(slot),
        room?.name ?? "—",
        `${subj.name}${subj.code ? `\n${subj.code}` : ""}`,
        chief + (a.sharedChief ? " (Shared)" : ""),
        invigilators,
      ];
    }));
    autoTable(doc, {
      startY: 92,
      head: [["Time Slot", "Room", "Subject (Code)", "Chief Invigilator", "Invigilators"]],
      body: rows,
      theme: "grid",
      headStyles: { fillColor: [241, 245, 249], textColor: [31, 64, 135], fontStyle: "bold", fontSize: 9 },
      bodyStyles: { fontSize: 9, cellPadding: 6, valign: "top" },
      alternateRowStyles: { fillColor: [250, 250, 252] },
      margin: { left: 40, right: 40 },
      columnStyles: { 0: { cellWidth: 90 }, 1: { cellWidth: 90 }, 2: { cellWidth: 150 }, 3: { cellWidth: 170 } },
    });
    drawFooter();
  }
  const filename = opts.mode === "single"
    ? `${brand.appName}_${opts.date}.pdf`
    : `${brand.appName}_FullSchedule_${format(new Date(), "yyyy-MM-dd")}.pdf`;
  doc.save(filename);
  return filename;
}

export function exportXlsx(ctx: ExportContext, opts: { mode: "single" | "full"; date?: string }) {
  const { schedule, staff, rooms, slots, brand } = ctx;
  const staffMap = new Map(staff.map((s) => [s.id, s]));
  const roomMap = new Map(rooms.map((r) => [r.id, r]));
  const slotMap = new Map(slots.map((s) => [s.id, s]));

  const filtered = opts.mode === "single"
    ? schedule.filter((e) => e.date === opts.date)
    : schedule;
  const sorted = [...filtered].sort((a, b) => a.date.localeCompare(b.date) || a.slotId.localeCompare(b.slotId));

  const scheduleRows: (string | number)[][] = [
    ["Day", "Date", "Time", "Room", "Subject", "Code", "Chief Invigilator", "Invigilators"],
  ];
  for (const e of sorted) {
    const slot = slotMap.get(e.slotId);
    for (const a of e.assignments) {
      const room = roomMap.get(a.roomId);
      const subj = subjectFor(a, slot);
      const chief = a.chiefInvigilatorId ? staffMap.get(a.chiefInvigilatorId)?.name ?? "—" : "UNASSIGNED";
      const invigilators = a.invigilatorIds.map((id) => id ? staffMap.get(id)?.name ?? "—" : "Missing").join(", ");
      scheduleRows.push([
        e.day, e.date, timeLabel(slot), room?.name ?? "—", subj.name, subj.code,
        chief + (a.sharedChief ? " (Shared)" : ""), invigilators,
      ]);
    }
  }

  // Workload summary
  const workload = new Map<string, { name: string; role: string; chief: number; inv: number }>();
  for (const person of staff) workload.set(person.id, { name: person.name, role: person.role === "CHIEF_INVIGILATOR" ? "Chief Invigilator" : "Invigilator", chief: 0, inv: 0 });
  for (const e of filtered) {
    for (const a of e.assignments) {
      if (a.chiefInvigilatorId && workload.has(a.chiefInvigilatorId)) workload.get(a.chiefInvigilatorId)!.chief++;
      a.invigilatorIds.forEach((id) => { if (id && workload.has(id)) workload.get(id)!.inv++; });
    }
  }
  const workloadRows: (string | number)[][] = [["Name", "Role", "As Chief", "As Invigilator", "Total"]];
  [...workload.values()]
    .sort((a, b) => (b.chief + b.inv) - (a.chief + a.inv) || a.name.localeCompare(b.name))
    .forEach((w) => workloadRows.push([w.name, w.role, w.chief, w.inv, w.chief + w.inv]));

  const wb = XLSX.utils.book_new();
  const ws1 = XLSX.utils.aoa_to_sheet(scheduleRows);
  ws1["!cols"] = [{ wch: 6 }, { wch: 12 }, { wch: 14 }, { wch: 14 }, { wch: 26 }, { wch: 10 }, { wch: 24 }, { wch: 50 }];
  // Header style hint via cell formatting (xlsx CE does not write styles but freeze + filter still help)
  ws1["!freeze"] = { xSplit: 0, ySplit: 1 } as any;
  ws1["!autofilter"] = { ref: XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: 0, c: scheduleRows[0].length - 1 } }) };
  XLSX.utils.book_append_sheet(wb, ws1, "Full Schedule");

  const ws2 = XLSX.utils.aoa_to_sheet(workloadRows);
  ws2["!cols"] = [{ wch: 26 }, { wch: 18 }, { wch: 12 }, { wch: 16 }, { wch: 10 }];
  ws2["!autofilter"] = { ref: XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: 0, c: workloadRows[0].length - 1 } }) };
  XLSX.utils.book_append_sheet(wb, ws2, "Workload Summary");

  const filename = opts.mode === "single"
    ? `${brand.appName}_${opts.date}.xlsx`
    : `${brand.appName}_FullSchedule_${format(new Date(), "yyyy-MM-dd")}.xlsx`;
  XLSX.writeFile(wb, filename);
  return filename;
}